name: "GodzK Custom Action"
description: "A custom action for updating stats"
inputs:
  WAKATIME_API_KEY:
    description: "WakaTime API Key"
    required: true
  GH_TOKEN:
    description: "GitHub Token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
