name: Daily Reminder

on:
  schedule:
    - cron: '30 7 * * *' # ทุกวันตอน 7 โมงครึ่ง

env:
  LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
  WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
  USER_ID: ${{ secrets.USER_ID }}

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install axios
      - name: Send Reminder
        run: node send.js
