name: Streak and Items Update

on:
  schedule:
    - cron: '0 */6 * * *'  # รันทุก 6 ชั่วโมง
  workflow_dispatch:       # สามารถกดรันเองได้จากหน้า GitHub

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Initialize or update reward.json
        run: |
          if [ ! -f reward.json ]; then
            echo '{"streak": 0, "gold": 0}' > reward.json
          fi
          node -e "
            let playerData = require('./reward.json');
            playerData.streak++;
            playerData.gold += 10;
            require('fs').writeFileSync('reward.json', JSON.stringify(playerData, null, 2));
          "
          cat reward.json  # Debug log

      - name: Initialize or update item.json
        run: |
          if [ ! -f item.json ]; then
            echo '{"items": {"sword": 1, "shield": 0}}' > item.json
          fi
          node -e "
            let itemData = require('./item.json');
            itemData.items.shield++;  // เพิ่ม shield
            require('fs').writeFileSync('item.json', JSON.stringify(itemData, null, 2));
          "
          cat item.json  # Debug log

      - name: Commit and push changes
        run: |
          git config --global user.name "GodzK"
          git config --global user.email "godzk25@gmail.com"
          git add reward.json item.json
          git commit -m "Streak and Items Update - $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
