name: Streak and Items Update

on:
  schedule:
    - cron: '0 */6 * * *'  # ทุก 6 ชั่วโมง
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Initialize or update reward.json
        run: |
          if [ ! -f reward.json ]; then
            echo '{"streak": 0, "gold": 0}' > reward.json
          fi
          node -e "
            let playerData = require('./reward.json');
            playerData.streak++;
            playerData.gold += 10;
            require('fs').writeFileSync('reward.json', JSON.stringify(playerData, null, 2));
          "
          cat reward.json  # Debug

      - name: Initialize or update item.json
        run: |
          if [ ! -f item.json ]; then
            echo '{"items": {"sword": 1, "shield": 0}}' > item.json
          fi
          node -e "
            let itemData = require('./item.json');
            itemData.items.shield++;  // เพิ่ม shield เป็นตัวอย่าง
            require('fs').writeFileSync('item.json', JSON.stringify(itemData, null, 2));
          "
          cat item.json  # Debug

      - name: Ensure sections exist in README.md
        run: |
          if ! grep -q "## My Game Streak" README.md; then
            echo "## My Game Streak" >> README.md
            echo "Streak: 0" >> README.md
            echo "Gold: 0" >> README.md
          fi
          if ! grep -q "## My Items" README.md; then
            echo "## My Items" >> README.md
            echo "Sword: 0" >> README.md
            echo "Shield: 0" >> README.md
          fi
          cat README.md  # Debug

      - name: Update README with streak and items
        run: |
          # อัปเดต Streak และ Gold
          STREAK=$(jq .streak reward.json)
          GOLD=$(jq .gold reward.json)
          sed -i "s/Streak: [0-9]*/Streak: $STREAK/" README.md
          sed -i "s/Gold: [0-9]*/Gold: $GOLD/" README.md
          # อัปเดต Items
          SWORD=$(jq .items.sword item.json)
          SHIELD=$(jq .items.shield item.json)
          sed -i "s/Sword: [0-9]*/Sword: $SWORD/" README.md
          sed -i "s/Shield: [0-9]*/Shield: $SHIELD/" README.md
          cat README.md  # Debug

      - name: Commit and push changes
        run: |
          git config --global user.name "GodzK"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add reward.json item.json README.md
          git commit -m "Updated stats - $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git pull --rebase origin main  # แก้ conflict
          git push
