name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 */6 * * *'  # อัปเดตทุก 6 ชั่วโมง (แก้จาก */3 เป็น */6 เพื่อให้ถูกต้องตาม cron syntax)
  workflow_dispatch:       # รัน manual ได้

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # อัปเดตเป็น v4 ซึ่งเป็นเวอร์ชันล่าสุด

      - name: Update WakaTime stats
        uses: athul/waka-readme@master  # ใช้ action ที่มีอยู่จริงจาก athul
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_TIMEZONE: "False"
          SECTION_NAME: "waka"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          COMMIT_MESSAGE: "Updated WakaTime stats"
