name: WakaTime and Streak Update

on:
  schedule:
    - cron: '0 */6 * * *'  # ทุก 6 ชั่วโมง
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Initialize or update reward.json
        run: |
          if [ ! -f reward.json ]; then
            echo '{"streak": 0, "gold": 0}' > reward.json
          fi
          cat reward.json  # Debug

      - name: Update streak data
        run: |
          node -e "
            let playerData = require('./reward.json');
            playerData.streak++;
            playerData.gold += 10;
            require('fs').writeFileSync('reward.json', JSON.stringify(playerData, null, 2));
          "

      - name: Prepare README with WakaTime section
        run: |
          echo "# My Profile" > README.md
          echo "## My WakaTime Stats" >> README.md
          echo "<!--START_SECTION:waka-->" >> README.md
          echo "<!--END_SECTION:waka-->" >> README.md
          echo "## My Game Streak" >> README.md
          echo "Streak: $(jq .streak reward.json)" >> README.md
          echo "Gold: $(jq .gold reward.json)" >> README.md

      - name: Update WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ใช้ token จาก GitHub Actions
          COMMIT_MESSAGE: "Updated WakaTime and Streak stats"
          SHOW_LINES_OF_CODE: "True"  # แสดงจำนวนบรรทัดโค้ด
          SHOW_LANGUAGE: "True"      # แสดงภาษาที่ใช้
          SHOW_TOTAL_CODE_TIME: "True"  # แสดงเวลารวม

      - name: Commit and push changes
        run: |
          git config --global user.name "GodzK"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add reward.json README.md
          git commit -m "Updated stats - $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git pull --rebase origin main  # ดึงและรวมการเปลี่ยนแปลงจาก remote
          git push
