name: WakaTime and Streak Update

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Fetch and update reward.json
        run: |
          curl -H "Authorization: token ${{ secrets.PAT }}" \
          https://raw.githubusercontent.com/GodzK/Streak-Farmer-RPG/main/reward.json > reward.json || echo '{"streak": 0, "gold": 0}' > reward.json
          node -e "
            let playerData = require('./reward.json');
            playerData.streak++;
            playerData.gold += 10;
            require('fs').writeFileSync('reward.json', JSON.stringify(playerData, null, 2));
          "

      - name: Update WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "Updated WakaTime stats"

      - name: Commit changes
        run: |
          echo "## My Game Streak" >> README.md
          echo "Streak: $(jq .streak reward.json)" >> README.md
          echo "Gold: $(jq .gold reward.json)" >> README.md
          git config --global user.name "GodzK"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add reward.json README.md
          git commit -m "Updated stats - $(date -u +'%Y-%m-%d')"
          git push

      - name: Install jq
        run: sudo apt-get install jq
